# Generated by Django 5.0.2 on 2024-03-01 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Products",
        ),
    ]
