# Generated by Django 5.0.2 on 2024-03-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account_details",
            old_name="Emails",
            new_name="Email",
        ),
        migrations.CreateModel(
            name="User_Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Password", models.TextField()),
                (
                    "Email",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="App.account_details",
                    ),
                ),
            ],
        ),
    ]
