# Generated by Django 5.0.2 on 2024-03-03 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0004_rename_emails_account_details_email_user_credential"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_credential",
            name="Email",
        ),
        migrations.DeleteModel(
            name="Account_Details",
        ),
        migrations.DeleteModel(
            name="User_Credential",
        ),
    ]
