# Generated by Django 5.0.2 on 2024-03-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("App", "0005_remove_user_credential_email_delete_account_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=50)),
                ("Contact_no", models.IntegerField(verbose_name=12)),
                ("Address", models.TextField()),
                ("Password", models.TextField()),
            ],
        ),
    ]
